In [2]:
import sqlite3

In [4]:
import pandas as pd
import numpy as np

path1 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\borse.csv'
path2 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdsll.csv'
path3 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdslpts.csv'
path4 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdsul.csv'
path5 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\thresholdsupts.csv'
path6 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\commercial.csv'
path7 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\ReviewTriggerLevels.csv'
path8 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\signalnarrativewithinsert.csv'
path9 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\HighRiskCodes.csv'
path10 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\BSv2.csv'
path11 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\actions.csv'
path12 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\NBA_scorecard.csv'
path13 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\OpenBanking.csv'
path14 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\PnLv2.csv'
#path15 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\BSv2.csv'
path16 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\PnLv2_T.csv'
path17 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\BSv2_T.csv'
path18 = r'C:\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\invoicev2.csv'

borse_df = pd.read_csv(path1)
thresholdsll_df = pd.read_csv(path2)
thresholdslpts_df = pd.read_csv(path3)
thresholdsul_df = pd.read_csv(path4)
thresholdsupts_df = pd.read_csv(path5)
commercial_df = pd.read_csv(path6,  parse_dates=["date of incorporation"])
review_trigger_levels_df = pd.read_csv(path7)
signal_narrative_df = pd.read_csv(path8)
high_risk_codes_df = pd.read_csv(path9)
BS_df = pd.read_csv(path10)
actions_df = pd.read_csv(path11)
NBA_scorecard_df = pd.read_csv(path12)
OpenBanking_df = pd.read_csv(path13, parse_dates=["open date"])
PnL_df = pd.read_csv(path14)
PnL_T_df = pd.read_csv(path16)
BS_T_df = pd.read_csv(path17)
invoice_df = pd.read_csv(path18)

print(borse_df)
#print(thresholdsll_df)
#print(thresholdslpts_df)
#print(thresholdsul_df)
#print(thresholdsupts_df)
#print(commercial_df)
#print(review_trigger_levels_df)
#print(signal_narrative_df)
#print(high_risk_codes_df)
#print(BS_df)
#print(actions_df)
#print(NBA_scorecard_df)
#print(OpenBanking_df)
#print(PnL_T_df)
#print(BS_T_df)


   id  share price
0   1           23


In [6]:
conn = sqlite3.connect('TestDB9.db') 
c = conn.cursor()
borse_df.to_sql('borse', conn, if_exists='replace', index = False)
thresholdsll_df.to_sql('thresholdsll', conn, if_exists='replace', index = False)
thresholdslpts_df.to_sql('thresholdslpts', conn, if_exists='replace', index = False)
thresholdsul_df.to_sql('thresholdsul', conn, if_exists='replace', index = False)
thresholdsupts_df.to_sql('thresholdsupts', conn, if_exists='replace', index = False)
commercial_df.to_sql('commercial', conn, if_exists='replace', index = False)
review_trigger_levels_df.to_sql('review_trigger_levels', conn, if_exists='replace', index = False)
signal_narrative_df.to_sql('signal_narrative', conn, if_exists='replace', index = False)
high_risk_codes_df.to_sql('high_risk_codes', conn, if_exists='replace', index = False)
BS_df.to_sql('BS', conn, if_exists='replace', index = False)
actions_df.to_sql('actions', conn, if_exists='replace', index = False)
NBA_scorecard_df.to_sql('NBA_scorecard', conn, if_exists='replace', index = False)
OpenBanking_df.to_sql('OpenBanking', conn, if_exists='replace', index = False)
PnL_df.to_sql('PnL', conn, if_exists='replace', index = False)
BS_T_df.to_sql('BS_T', conn, if_exists='replace', index = False)
PnL_T_df.to_sql('PnL_T', conn, if_exists='replace', index = False)
invoice_df.to_sql('invoice', conn, if_exists='replace', index = False)

In [7]:
c.execute('''  
SELECT * FROM PnL_T
          ''')

In [9]:
import pandas as pd

c = conn.cursor()
q = """
SELECT *
FROM PnL_T
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
PnL_T_df = pd.DataFrame(c.fetchall(), columns=cols)
PnL_T_df.head()

print(cols)

['Party_id', 'Month', 'Sales', 'Direct Cost of Sales', 'Production Payroll', 'Other', 'Total Cost of Sales', 'Gross Margin', 'Gross Margin %', 'Operating Expenses:', 'Sales and Marketing Expenses', 'Sales and Marketing Payroll', 'Rent', 'Travel', 'Burglar Alarm', 'Total Sales & Marketing Expenses', 'Sales and Marketing %', 'General and Administrative Expenses', 'General & Administrative Payroll', 'Payroll Expense', 'Payroll Burden', 'Depreciation', 'Office Supplies', 'Utilities', 'Insurance', 'Telephone', 'Total General & Administrative Expenses', 'General and Administrative %', 'Other Expenses', 'Other Payroll', 'Advertising', 'Loan Repayment', 'Inventory', 'Accounting/legal', 'Total Other Expenses', 'Other %', 'Total Operating Expenses', 'Profit Before Interest and Taxes', 'Interest Expense Short-term', 'Interest Expense Long-term', 'Taxes Incurred', 'Extraordinary Items', 'Net Profit', 'Net Profit/Sales']


In [30]:
c.close()

In [31]:
conn.commit()
c.close()

In [32]:
c = conn.cursor()
q = """
SELECT *
FROM thresholdslpts
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
df = pd.DataFrame(c.fetchall(), columns=cols)
df.head()

lower breach  Conduct  Liquidity  Credit  Capital  \
0          DirectorDisqualified      NaN        NaN     3.0      NaN   
1                   DirectorCCJ      NaN        NaN     3.0      NaN   
2            DirectorBankcrupcy      NaN        NaN     3.0      NaN   
3      CreditScoreAndNoSecurity      NaN        NaN     3.0      NaN   
4  ValueLoanOutstandingLtvRatio      NaN        NaN     3.0      NaN   

   Contagion  Trade  AML  Fraud  
0        NaN    NaN  NaN    NaN  
1        NaN    NaN  NaN    NaN  
2        NaN    NaN  NaN    NaN  
3        NaN    NaN  NaN    NaN  
4        NaN    NaN  NaN    NaN

In [10]:
c = conn.cursor()
q = """
SELECT *
FROM BS_T
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
BS_T_df = pd.DataFrame(c.fetchall(), columns=cols)
BS_T_df.head()

print(cols)

#print(BS_T_df)

['Party_id', 'Month', 'Assets', 'Short-term Assets', 'Cash', 'Accounts Receivable', 'Inventory', 'Other Short-term Assets', 'Total Short-term Assets', 'Long-term Assets', 'Capital Assets', 'Accumulated Depreciation', 'Total Long-term Assets', 'Total Assets', 'Liabilities and Capital', 'Accounts Payable', 'Short-term Notes', 'Other Short-term Liabilities', 'Subtotal Short-term Liabilities', 'Long-term Liabilities', 'Total Liabilities', 'Paid in Capital', 'Dividends paid', 'Retained Earnings', 'Earnings', 'Total Capital', 'Total Liabilities and Capital', 'Net Worth']


In [34]:
c = conn.cursor()
q = """
SELECT *
FROM borse
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
borse_df = pd.DataFrame(c.fetchall(), columns=cols)
borse_df.head()


id  share price
0   1           23

In [35]:
c = conn.cursor()
q = """
SELECT *
FROM commercial
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
commercial_df = pd.DataFrame(c.fetchall(), columns=cols)
commercial_df.head()


print(commercial_df)

   party_id  disqualified director  bankcrupt director  CCJ director  \
0         0                      1                   1             1   
1         1                      0                   0             0   

   changed director  credit score  new business director  \
0                 1           650                      1   
1                 0           460                      0   

   regional economy index date of incorporation postcode  
0                       8   2010-01-01 00:00:00      EH5  
1                       6   2019-03-05 00:00:00      EC4  


In [11]:
c = conn.cursor()
q = """
SELECT *
FROM invoice
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
invoice_df = pd.DataFrame(c.fetchall(), columns=cols)
invoice_df.head()

print(cols)

['Id', 'PartyId', 'CustomerId', 'SequenceNumber', 'InvoiceReference', 'DueDate', 'CreatedDate', 'RaisedDate', 'ReceivedValue', 'IsInsured', 'CurrencyCode', 'CurrencyRate', 'ModifiedDate', 'PaidDate', 'NetValue', 'DiscountValue', 'DiscountPercent', 'GrossValue', 'TaxValue', 'OutstandingAmountValue', 'ValidDate', 'Status', 'DaysToPay', 'Customer credit score']


In [37]:
c = conn.cursor()
q = """
SELECT *
FROM high_risk_codes
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
high_risk_codes_df = pd.DataFrame(c.fetchall(), columns=cols)
high_risk_codes_df.head()


high risk sic code
0                  23
1                  45
2                 654

In [38]:
import numpy as np
import pandas as pd

months = []
for i in range(36) : months.append(i)
    
BS_line_items= pd.Series(BS_T_df.columns)
PnL_line_items= pd.Series(PnL_T_df.columns)

#print(BS_line_items)
print(PnL_line_items)

0                                    Party_id
1                                       Month
2                                       Sales
3                        Direct Cost of Sales
4                          Production Payroll
5                                       Other
6                         Total Cost of Sales
7                                Gross Margin
8                              Gross Margin %
9                         Operating Expenses:
10               Sales and Marketing Expenses
11                Sales and Marketing Payroll
12                                       Rent
13                                     Travel
14                              Burglar Alarm
15           Total Sales & Marketing Expenses
16                      Sales and Marketing %
17        General and Administrative Expenses
18           General & Administrative Payroll
19                            Payroll Expense
20                             Payroll Burden
21                               D

In [39]:
c = conn.cursor()
q = """
SELECT distinct(Party_id)
FROM BS_T
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
companies_df = pd.DataFrame(c.fetchall(), columns=cols)
companies_df.head()

companies_s = pd.Series(companies_df["Party_id"])

for company in companies_s : print(company)
    
    

1
2


In [40]:
c = conn.cursor()
q = """
SELECT *
FROM borse
"""
c.execute(q)
cols = [desc[0] for desc in c.description]
borse_df = pd.DataFrame(c.fetchall(), columns=cols)
borse_df.head()

id  share price
0   1           23

In [41]:

for n, company in enumerate(companies_s) :
    if n == 0 : 
        BS = BS_T_df.loc[BS_T_df['Party_id'] == company].T.to_numpy()
        PnL = PnL_T_df.loc[PnL_T_df['Party_id'] == company].T.to_numpy()
    else :     
        BS_next = BS_T_df.loc[BS_T_df['Party_id'] == company].T.to_numpy()
        BS = np.stack((BS, BS_next), axis= 2)
        PnL_next = PnL_T_df.loc[PnL_T_df['Party_id'] == company].T.to_numpy()
        PnL = np.stack((PnL, PnL_next), axis= 2)
        
#print(BS)
#print(PnL)

In [42]:
#np.shape(BS)
#print(BS[:,0,1])
months = BS[1, :, 1]
print(months)

['17-Dec' '18-Jan' '18-Feb' '18-Mar' '18-Apr' '18-May' '18-Jun' '18-Jul'
 '18-Aug' '18-Sep' '18-Oct' '18-Nov' '18-Dec' '19-Jan' '19-Feb' '19-Mar'
 '19-Apr' '19-May' '19-Jun' '19-Jul' '19-Aug' '19-Sep' '19-Oct' '19-Nov'
 '19-Dec' '20-Jan' '20-Feb' '20-Mar' '20-Apr' '20-May' '20-Jun' '20-Jul'
 '20-Aug' '20-Sep' '20-Oct' '20-Nov']


In [43]:
PnL_key_line_items = [
"Sales",
"Total Cost of Sales",
"Gross Margin",
"Total Sales & Marketing Expenses",
"Rent",
"Payroll Expense",
"Total General & Administrative Expenses",
"Loan Repayment",
"Inventory",
"Depreciation",
"Total Operating Expenses",
"Profit Before Interest and Taxes",
"Interest Expense Short-term",
"Interest Expense Long-term",
"Taxes Incurred",
"Extraordinary Items",
"Net Profit",
]


BS_key_line_items = [
"Accounts Receivable",
"Inventory",
"Other Short-term Assets",
"Total Short-term Assets",    
"Long-term Assets",
"Total Assets",
"Cash",
"Accounts Payable",
"Short-term Notes",
"Other Short-term Liabilities",
"Subtotal Short-term Liabilities",    
"Long-term Liabilities",
"Total Liabilities",
"Paid in Capital",
"Dividends paid",
"Retained Earnings",    
"Earnings",    
"Total Capital",   
"Net Worth"    
]



PnL_st = set(PnL_key_line_items)
PnL_line_indices =  {e:i for i, e in enumerate(PnL_line_items) if e in PnL_st}

BS_st = set(BS_key_line_items)
BS_line_indices = {e:i for i, e in enumerate(BS_line_items) if e in BS_st}

print(PnL_line_indices)
print(BS_line_indices)


{'Sales': 2, 'Total Cost of Sales': 6, 'Gross Margin': 7, 'Rent': 12, 'Total Sales & Marketing Expenses': 15, 'Payroll Expense': 19, 'Depreciation': 21, 'Total General & Administrative Expenses': 26, 'Loan Repayment': 31, 'Inventory': 32, 'Total Operating Expenses': 36, 'Profit Before Interest and Taxes': 37, 'Interest Expense Short-term': 38, 'Interest Expense Long-term': 39, 'Taxes Incurred': 40, 'Extraordinary Items': 41, 'Net Profit': 42}
{'Cash': 4, 'Accounts Receivable': 5, 'Inventory': 6, 'Other Short-term Assets': 7, 'Total Short-term Assets': 8, 'Long-term Assets': 9, 'Total Assets': 13, 'Accounts Payable': 15, 'Short-term Notes': 16, 'Other Short-term Liabilities': 17, 'Subtotal Short-term Liabilities': 18, 'Long-term Liabilities': 19, 'Total Liabilities': 20, 'Paid in Capital': 21, 'Dividends paid': 22, 'Retained Earnings': 23, 'Earnings': 24, 'Total Capital': 25, 'Net Worth': 27}


In [44]:
print(BS_line_items)

0                            Party_id
1                               Month
2                              Assets
3                   Short-term Assets
4                                Cash
5                 Accounts Receivable
6                           Inventory
7             Other Short-term Assets
8             Total Short-term Assets
9                    Long-term Assets
10                     Capital Assets
11           Accumulated Depreciation
12             Total Long-term Assets
13                       Total Assets
14            Liabilities and Capital
15                   Accounts Payable
16                   Short-term Notes
17       Other Short-term Liabilities
18    Subtotal Short-term Liabilities
19              Long-term Liabilities
20                  Total Liabilities
21                    Paid in Capital
22                     Dividends paid
23                  Retained Earnings
24                           Earnings
25                      Total Capital
26      Tota

In [45]:
PnL.shape

(44, 36, 2)

In [46]:
PnL_key_lines = PnL[list(PnL_line_indices.values()), :, :]
BS_key_lines = BS[list(BS_line_indices.values()), :, :]
#PnL_key_lines.shape
#print(BS_key_lines)
#print(PnL_key_lines)

In [47]:
#print(BS_line_indices["Total Short-term Assets"])
#print(TotalCurrentAssetsValue)

TotalCurrentAssetsValue = BS[BS_line_indices["Total Short-term Assets"], :, :]

print(TotalCurrentAssetsValue)

[[53272.46377 53272.46377]
 [40861.1117 40861.1117]
 [39972.7196 39972.7196]
 [34328.31045 34328.31045]
 [30745.495160000002 30745.495160000002]
 [26641.54423 26641.54423]
 [17605.50488 17605.50488]
 [11481.95935 11481.95935]
 [6744.490490000001 6744.490490000001]
 [3987.857693 3987.857693]
 [-3286.6657649999997 -3286.6657649999997]
 [3069.67825 3069.67825]
 [9922.869469 9922.869469]
 [-2611.096582 -2611.096582]
 [-3693.0808869999996 -3693.0808869999996]
 [-10229.66697 -10229.66697]
 [-13498.974069999998 -13498.974069999998]
 [-19131.066730000002 -19131.066730000002]
 [-27296.02863 -27296.02863]
 [-35000.69152 -35000.69152]
 [-38851.03584 -38851.03584]
 [-43527.1789 -43527.1789]
 [-49414.26613 -49414.26613]
 [-146211.9271 -146211.9271]
 [-137648.2855 -137648.2855]
 [-151341.279 -151341.279]
 [-153739.8848 -153739.8848]
 [-161158.235 -161158.235]
 [-165843.3544 -165843.3544]
 [-171852.277 -171852.277]
 [-181284.1239 -181284.1239]
 [-188792.5867 -188792.5867]
 [-194602.6417 -194602.6417]

In [52]:
SalesValue = PnL[PnL_line_indices["Sales"], :, :]
DirectCostofSalesValue = PnL[PnL_line_indices["Total Cost of Sales"], :, :]
TotalCurrentAssetsValue = BS[BS_line_indices["Total Short-term Assets"], :, :]
TotalCurrentLiabilitiesValue = BS[BS_line_indices["Subtotal Short-term Liabilities"], :, :]
TotalEquityValue = BS[BS_line_indices["Total Capital"], :, :]
LongTermLiabilitiesValue =  BS[BS_line_indices["Long-term Liabilities"], :, :]
OperatingExpensesValue =  PnL[PnL_line_indices["Total Operating Expenses"], :, :]
TotalNetAssetsValue =  BS[BS_line_indices["Total Assets"], :, :] - BS[BS_line_indices["Total Liabilities"], :, :]
TotalFixedAssetValue =  BS[BS_line_indices["Long-term Assets"], :, :]
TotalIncomeValue = PnL[PnL_line_indices["Sales"], :, :]
OtherIncomeValue =  np.zeros(np.shape(TotalIncomeValue))
OwnersFundsValue =  BS[BS_line_indices["Total Capital"], :, :]
#SalesValue = PnL_key_lines[PnL_key_line_items.index("Sales"), :, :]
DepreciationValue =  PnL[PnL_line_indices["Depreciation"], :, :]
OperatingCostsValue =  PnL[PnL_line_indices["Total Operating Expenses"], :, :]
PBITValue = PnL[PnL_line_indices["Profit Before Interest and Taxes"], :, :]
InterestValue = PnL[PnL_line_indices["Interest Expense Short-term"], :, :] + PnL[PnL_line_indices["Interest Expense Long-term"], :, :]
TaxValue = PnL[PnL_line_indices["Taxes Incurred"], :, :]
PATValue = PnL[PnL_line_indices["Net Profit"], :, :]
PaidInCapitalValue = BS[BS_line_indices["Paid in Capital"], :, :]
DividendValue = BS[BS_line_indices["Dividends paid"], :, :]
RetainedEarningsValue = BS[BS_line_indices["Retained Earnings"], :, :]
EarningsValue = BS[BS_line_indices["Earnings"], :, :]
OrdinaryShareNumber =  np.zeros(np.shape(TotalIncomeValue)) 
OrdinarySharePriceValue =  np.zeros(np.shape(TotalIncomeValue)) 
InventoryValue = BS[BS_line_indices["Inventory"], :, :]
DebtValue = BS[BS_line_indices["Short-term Notes"], :, :]
CashValue = BS[BS_line_indices["Cash"], :, :]
NetWorthValue = BS[BS_line_indices["Net Worth"], :, :]
RentValue = PnL[PnL_line_indices["Rent"], :, :]
PayRollValue = PnL[PnL_line_indices["Payroll Expense"], :, :]



#print(Sales)

In [53]:
ROIRatio = PATValue / TotalEquityValue
ROTARatio = PATValue / TotalNetAssetsValue
CurrentRatio = TotalCurrentAssetsValue / TotalCurrentLiabilitiesValue
QuickRatio = (TotalCurrentAssetsValue - InventoryValue) / TotalCurrentLiabilitiesValue
WorkingCapitalSalesRatio = (TotalCurrentAssetsValue - TotalCurrentLiabilitiesValue) / SalesValue
InterestCoverRatio = PBITValue / InterestValue
DebtToEquityRatio = DebtValue / TotalEquityValue
LeverageRatio = TotalEquityValue / (DebtValue + TotalEquityValue)
TotalIncomeValue = SalesValue
TotalCostofSalesValue = DirectCostofSalesValue
GrossProfitValue = SalesValue - DirectCostofSalesValue
ROERatio = PATValue / TotalEquityValue
ROCERatio = (PBITValue + DebtValue) / TotalEquityValue
TotalLoanBalanceValue = DebtValue
TotalRevenueValue = SalesValue
BlendedTermInterestRate =  InterestValue / DebtValue
#ChangeInInventoryToChangeInSales = 
ClosingCashBalanceValue =  CashValue
HighDividendReleaseRatio = DividendValue / TotalEquityValue                                            
LargeVATBillToCapitalRatio =  TaxValue / TotalEquityValue    
MarginRate = GrossProfitValue / SalesValue
LoansToSalesRatio = DebtValue / SalesValue
#NetWorthValue =                                           
PayRollToSalesRatio = PayRollValue / SalesValue
RentToSalesRatio = RentValue / SalesValue    
VolitileEarningsValue = EarningsValue / TotalEquityValue                                            
#WorkingCapitaltoSalesRatio =     

first_mth = np.empty((1, len(companies_s)))
SalesGrowthRate =  np.concatenate((first_mth, SalesValue[1:, :] - SalesValue[:-1, :]), axis=0)
InventoryGrowthRate =  np.concatenate((first_mth, InventoryValue[1:, :] - InventoryValue[:-1, :]), axis=0) 

ChangeInInventoryToChangeInSales = np.empty_like(SalesGrowthRate)
mask = (SalesGrowthRate == 0)
ChangeInInventoryToChangeInSales[mask] = np.zeros(np.shape(ChangeInInventoryToChangeInSales))[mask]
ChangeInInventoryToChangeInSales[~mask] = InventoryGrowthRate[~mask]/SalesGrowthRate[~mask]

StockDaysValue = np.empty_like(DirectCostofSalesValue)
mask = (DirectCostofSalesValue == 0)
StockDaysValue[mask] = np.zeros(np.shape(StockDaysValue))[mask]
StockDaysValue[~mask] = (InventoryValue[~mask] * 30)/DirectCostofSalesValue[~mask]

In [54]:
#print(BS_key_lines[BS_key_line_items.index("Total Short-term Assets"), :, :] )
print(BS_key_line_items.index("Total Short-term Assets") )

3


In [57]:
Allpnl_array = np.concatenate((SalesValue, 
                               DirectCostofSalesValue,
                               TotalCurrentAssetsValue,
                               TotalCurrentLiabilitiesValue,
                               TotalEquityValue,
                               LongTermLiabilitiesValue,
                               OperatingExpensesValue,
                               TotalNetAssetsValue,
                               TotalFixedAssetValue,
                               TotalIncomeValue,
                               OtherIncomeValue,
                               OwnersFundsValue,
                               SalesValue,
                               OperatingCostsValue,
                               PBITValue,
                               InterestValue,
                               TaxValue,
                               PATValue,
                               DividendValue,
                               RetainedEarningsValue,
                               OrdinaryShareNumber,
                               OrdinarySharePriceValue,
                               ROTARatio,
                               CurrentRatio,
                               QuickRatio,
                               WorkingCapitalSalesRatio,
                               InterestCoverRatio,
                               DebtToEquityRatio,
                               LeverageRatio,
                               TotalIncomeValue,
                               TotalCostofSalesValue,
                               GrossProfitValue,
                               ROERatio,
                               ROCERatio,
                               TotalLoanBalanceValue,
                               TotalRevenueValue,
                               BlendedTermInterestRate ,
                               ChangeInInventoryToChangeInSales , 
                               ClosingCashBalanceValue  ,   
                               HighDividendReleaseRatio ,                                             
                               LargeVATBillToCapitalRatio ,                                             
                               LoansToSalesRatio , 
                               NetWorthValue   ,                                           
                               PayRollToSalesRatio,
                               RentToSalesRatio ,                                             
                               StockDaysValue  ,                                            
                               VolitileEarningsValue ,                                             
                               SalesGrowthRate
                              ), axis = 0)

In [58]:
np.shape(Allpnl_array)

(1728, 2)

In [59]:
number_months = 36
number_companies = len(companies_s)
number_metrics = np.shape(Allpnl_array)[0] // number_months


Allpnl_reshape_array = np.moveaxis(np.reshape(Allpnl_array, (number_metrics , number_months, number_companies)), 1, 2 )

print(Allpnl_reshape_array[:3, :, :10])

[[[34107.692310000006 7366.863904999999 11668.07721 11352.65446
   10145.04628 10248.79877 6649.280866 6393.539294 11636.24151
   9816.622937]
  [34107.692310000006 7366.863904999999 11668.07721 11352.65446
   10145.04628 10248.79877 6649.280866 6393.539294 11636.24151
   9816.622937]]

 [[0 4750 0 4750 0 4750 0 4750 0 4750]
  [0 4750 0 4750 0 4750 0 4750 0 4750]]

 [[53272.46377 40861.1117 39972.7196 34328.31045 30745.495160000002
   26641.54423 17605.50488 11481.95935 6744.490490000001 3987.857693]
  [53272.46377 40861.1117 39972.7196 34328.31045 30745.495160000002
   26641.54423 17605.50488 11481.95935 6744.490490000001 3987.857693]]]


In [60]:
party_id = np.array([0] * number_months).T
party_id_reshape= np.reshape(party_id, (number_months,1 ))
months_list = list(months)
months_array= np.array(months_list)
months_reshape= np.reshape(months_array, (number_months,1 ))
header = ["Party_id", "Date"] + [str("metric_") + str(i) for i in range(1, number_metrics + 1)]
header_array = np.array(header)
header_reshape= np.reshape(header_array, (1, 2 + number_metrics))
first_block = np.concatenate((party_id_reshape, months_reshape, (Allpnl_reshape_array[:,0,:]).T ), axis = 1)
#np.shape(header_reshape)
#np.shape(first_block)

Alloutput_reshape_array = np.concatenate( (header_reshape, first_block), axis = 0)          
for i in range(1, number_companies) :
    party_id = np.array([i] * number_months).T
    party_id_reshape= np.reshape(party_id, (number_months,1 ))
    next_block = np.concatenate((party_id_reshape, months_reshape, (Allpnl_reshape_array[:,i,:]).T ), axis = 1)
    Alloutput_reshape_array = np.concatenate( (Alloutput_reshape_array, next_block), axis=0)

        
#np.shape(Alloutput_reshape_array)            

print(Alloutput_reshape_array[:40,: 5])

[['Party_id' 'Date' 'metric_1' 'metric_2' 'metric_3']
 [0 '17-Dec' 34107.692310000006 0 53272.46377]
 [0 '18-Jan' 7366.863904999999 4750 40861.1117]
 [0 '18-Feb' 11668.07721 0 39972.7196]
 [0 '18-Mar' 11352.65446 4750 34328.31045]
 [0 '18-Apr' 10145.04628 0 30745.495160000002]
 [0 '18-May' 10248.79877 4750 26641.54423]
 [0 '18-Jun' 6649.280866 0 17605.50488]
 [0 '18-Jul' 6393.539294 4750 11481.95935]
 [0 '18-Aug' 11636.24151 0 6744.490490000001]
 [0 '18-Sep' 9816.622937 4750 3987.857693]
 [0 '18-Oct' 10149.70206 0 -3286.6657649999997]
 [0 '18-Nov' 17566.792019999997 4750 3069.67825]
 [0 '18-Dec' 32508.443310000002 0 9922.869469]
 [0 '19-Jan' 7021.444765 4750 -2611.096582]
 [0 '19-Feb' 11120.981829999999 0 -3693.0808869999996]
 [0 '19-Mar' 10820.34869 4750 -10229.66697]
 [0 '19-Apr' 9669.363111 0 -13498.974069999998]
 [0 '19-May' 9768.250832 4750 -19131.066730000002]
 [0 '19-Jun' 6337.507917 0 -27296.02863]
 [0 '19-Jul' 6093.757613000001 4750 -35000.69152]
 [0 '19-Aug' 11090.63886 0 -38

In [61]:
header = ["Party_id", "Date"] + [str("metric_") + str(i) for i in range(1, number_metrics + 1)]
print(header)

['Party_id', 'Date', 'metric_1', 'metric_2', 'metric_3', 'metric_4', 'metric_5', 'metric_6', 'metric_7', 'metric_8', 'metric_9', 'metric_10', 'metric_11', 'metric_12', 'metric_13', 'metric_14', 'metric_15', 'metric_16', 'metric_17', 'metric_18', 'metric_19', 'metric_20', 'metric_21', 'metric_22', 'metric_23', 'metric_24', 'metric_25', 'metric_26', 'metric_27', 'metric_28', 'metric_29', 'metric_30', 'metric_31', 'metric_32', 'metric_33', 'metric_34', 'metric_35', 'metric_36', 'metric_37', 'metric_38', 'metric_39', 'metric_40', 'metric_41', 'metric_42', 'metric_43', 'metric_44', 'metric_45', 'metric_46', 'metric_47', 'metric_48']


In [62]:
import pandas as pd 


pd.DataFrame(Alloutput_reshape_array).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\Alloutput.csv", header=None, index=None)

metrics = Allpnl_reshape_array[:35, :,  -1]
np.shape(metrics)
#print(metrics)

(35, 2)

In [63]:
pd.DataFrame(Alloutput_reshape_array).to_sql('Alloutput', conn, if_exists='replace', index = False)

DatabaseError: Execution failed on sql 'DROP TABLE "Alloutput"': database table is locked

In [64]:

#placeholders for metrics to be sourced or calculated
CashflowChangeValue_array = np.reshape([0] * number_companies, (number_companies,1))
MLHighRiskSector_array = np.reshape([0] * number_companies, (number_companies,1))
LongSourcetoLongUseFunds_array = np.reshape([0] * number_companies, (number_companies,1))
NewDebtEquityToStockDebtEquity_array = np.reshape([0] * number_companies, (number_companies,1))
ShortSourceShortUseVsCurrentAssetsCurrentLiabilities_array = np.reshape([0] * number_companies, (number_companies,1))
OverseasCreditorsValueRatio_array = np.reshape([0] * number_companies, (number_companies,1))
NonOperationalAssetsValue_array = np.reshape([0] * number_companies, (number_companies,1))
DebtorDaysChangeValue_array = np.reshape([0] * number_companies, (number_companies,1))
CreditScoreAndNoSecurity_array = np.reshape([0] * number_companies, (number_companies,1))


#placeholders for metrics to be sourced or calculated
MetricLoanOutstandingLTVRatio_array = np.reshape([0] * number_companies, (number_companies,1))
MetricRiskMismatchPrice_array = np.reshape([0] * number_companies, (number_companies,1))


#print(CashflowChangeValue_array)

In [86]:

HasSustainableProfit = np.reshape((( MarginRate >= 0.10 ) * ( ROTARatio >= 1.30 ) *  ( ROTARatio <= 1.50 ))[-1, :], (number_companies, 1))

#print(MarginRate[:10,:])    
#print(ROTARatio[:10,:])    
#print(ROTARatio[:10,:])  
#print(HasSustainableProfit[:10,:])  
    

In [87]:
np.shape(HasSustainableProfit)

(2, 1)

In [68]:
this_month_ROCE = ROCERatio[:-1, :]
last_month_ROCE = ROCERatio[1:, :]

MetricROCEChangeValue = np.empty_like(this_month_ROCE)
mask = (last_month_ROCE == 0)
MetricROCEChangeValue[mask] = np.zeros(np.shape(MetricROCEChangeValue))[mask]
MetricROCEChangeValue[~mask] = (this_month_ROCE[~mask] - last_month_ROCE[~mask])/last_month_ROCE[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricROCEChangeValue = np.reshape(np.concatenate((a, MetricROCEChangeValue), axis=0)[-1, :], (number_companies, 1))
#np.shape(MetricROCEChangeValue)


this_month_ROTA = ROTARatio[:-1, :]
last_month_ROTA = ROTARatio[1:, :]

MetricROTAChangeValue = np.empty_like(this_month_ROTA)
mask = (last_month_ROTA == 0)
MetricROTAChangeValue[mask] = np.zeros(np.shape(MetricROTAChangeValue))[mask]
MetricROTAChangeValue[~mask] = (this_month_ROCE[~mask] - last_month_ROTA[~mask])/last_month_ROTA[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricROTAChangeValue = np.reshape(np.concatenate((a, MetricROTAChangeValue), axis=0)[-1, :], (number_companies, 1))
#np.shape(MetricROTAChangeValue)


this_month_ROTA = ROTARatio[:-1, :]
last_month_ROTA = ROTARatio[1:, :]

MetricROTAChangeValue = np.empty_like(this_month_ROTA)
mask = (last_month_ROTA == 0)
MetricROTAChangeValue[mask] = np.zeros(np.shape(MetricROTAChangeValue))[mask]
MetricROTAChangeValue[~mask] = (this_month_ROCE[~mask] - last_month_ROTA[~mask])/last_month_ROTA[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricROTAChangeValue = np.reshape(np.concatenate((a, MetricROTAChangeValue), axis=0)[-1, :], (number_companies, 1))
#np.shape(MetricROTAChangeValue)

this_month_Margin = MarginRate[:-1, :]
last_month_Margin = MarginRate[1:, :]

MetricMarginChange = np.empty_like(this_month_Margin)
mask = (last_month_Margin == 0)
MetricMarginChange[mask] = np.zeros(np.shape(MetricMarginChange))[mask]
MetricMarginChange[~mask] = (this_month_Margin[~mask] - last_month_Margin[~mask])/last_month_Margin[~mask]

a = np.empty((1, number_companies))
a[:] = np.nan

MetricMarginChange = np.reshape(np.concatenate((a, MetricMarginChange), axis=0)[-1, :], (number_companies, 1))

MetricChangeInInventoryToChangeInSales = np.reshape(ChangeInInventoryToChangeInSales[-1, :], (number_companies, 1))


In [70]:
np.shape(PATValue)

(36, 2)

In [71]:
#np.shape(MetricRiskMismatchPrice_array)
np.shape(np.reshape(np.array(commercial_df.iloc[:]["disqualified director"]), (number_companies,1)))
#np.shape(SalesGrowthRate)

(2, 1)

In [72]:
np.shape(invoice_df)
invoice_array = np.reshape(invoice_df, np.shape(invoice_df))
type(invoice_array)

unique_companies = np.unique(invoice_df["PartyId"])
unique_customers = np.unique(invoice_df["CustomerId"])
customer_concentration_ratio = [] 
sums = []
accum_sums = []
customer_concentration_ratios = []
last_sum = 0
for company in unique_companies :
   company_invoice_df = invoice_df[["GrossValue","CustomerId"]][invoice_df["PartyId"] == company ] 
   for customer in unique_customers :
      s = company_invoice_df["GrossValue"][company_invoice_df["CustomerId"] == customer].sum()
      sums.append(s)
   sums_rank = pd.Series(sums).rank()
   rank_2  = list(np.where(sums_rank == len(sums) - 2))[0]
   customer_concentration_ratio = max(sums / sums[rank_2[0]])
   customer_concentration_ratios.append(customer_concentration_ratio)

print(customer_concentration_ratios)    

MetricCustomerConcentrationRatios = np.reshape(customer_concentration_ratios, (number_companies, 1))
MetricSupplierConcentrationRatios = MetricCustomerConcentrationRatios

[1.0408319148007508, 1.0408319148007508]


In [73]:
print(MetricCustomerConcentrationRatios)

[[1.04083191]
 [1.04083191]]


In [74]:
# create metrics from commercial data
MetricDisqualifiedDirector = np.reshape(np.array(commercial_df.iloc[:]["disqualified director"]), (number_companies, 1))
MetricCCJDirector = np.reshape(np.array(commercial_df.iloc[:]["CCJ director"]), (number_companies, 1))
MetricBankcruptDirector = np.reshape(np.array(commercial_df.iloc[:]["bankcrupt director"]), (number_companies, 1))
MetricChangedDirector = np.reshape(np.array(commercial_df.iloc[:]["changed director"]), (number_companies, 1))
MetricNewBusinessDirector = np.reshape(np.array(commercial_df.iloc[:]["new business director"]), (number_companies, 1))
MetricRegionalEconomyIndex = np.reshape(np.array(commercial_df.iloc[:]["regional economy index"]), (number_companies, 1))


#metrics calculated from accounting data
MetricVolitileEarningsValue = np.reshape(VolitileEarningsValue[-1, :], (number_companies, 1))
MetricPATValue = np.reshape(PATValue[-1, :], (number_companies, 1))
MetricSalesGrowthRate = np.reshape(SalesGrowthRate[-1, :], (number_companies, 1))
MetricCurrentRatio = np.reshape(CurrentRatio[-1, :], (number_companies, 1))
MetricWorkingCapitalSalesRatio = np.reshape(WorkingCapitalSalesRatio[-1, :], (number_companies, 1))
MetricDebtToEquityRatio = np.reshape(DebtToEquityRatio[-1, :], (number_companies, 1))
MetricLoansToSalesRatio = np.reshape(LoansToSalesRatio[-1, :], (number_companies, 1))
MetricPayRollToSalesRatio = np.reshape(PayRollToSalesRatio[-1, :], (number_companies, 1))
MetricRentToSalesRatio = np.reshape(RentToSalesRatio[-1, :], (number_companies, 1))
MetricHighDividendReleaseRatio = np.reshape(HighDividendReleaseRatio[-1, :], (number_companies, 1))
MetricLargeVATBillToCapitalRatio = np.reshape(LargeVATBillToCapitalRatio[-1, :], (number_companies, 1))

In [84]:
np.shape(OverseasCreditorsValueRatio_array)

(2, 1)

In [75]:
np.shape(np.array(commercial_df.iloc[:]["disqualified director"]))
np.shape(CreditScoreAndNoSecurity_array)

(2, 1)

In [88]:
signals_array = np.concatenate((MetricDisqualifiedDirector,
                                MetricCCJDirector,
                                MetricBankcruptDirector,
                                CreditScoreAndNoSecurity_array,
                                MetricLoanOutstandingLTVRatio_array,
                                MetricChangedDirector,
                                MetricRiskMismatchPrice_array,
                                MetricVolitileEarningsValue,
                                MetricPATValue,
                                CashflowChangeValue_array,
                                MLHighRiskSector_array,
                                MetricROCEChangeValue,
                                MetricROTAChangeValue,
                                HasSustainableProfit,
                                MetricSalesGrowthRate,
                                MetricCurrentRatio,
                                MetricWorkingCapitalSalesRatio,
                                MetricDebtToEquityRatio,
                                LongSourcetoLongUseFunds_array,
                                NewDebtEquityToStockDebtEquity_array,
                                ShortSourceShortUseVsCurrentAssetsCurrentLiabilities_array,
                                MetricMarginChange,
                                MetricChangeInInventoryToChangeInSales,
                                MetricLoansToSalesRatio,
                                MetricPayRollToSalesRatio,
                                MetricRentToSalesRatio,
                                OverseasCreditorsValueRatio_array,
                                NonOperationalAssetsValue_array,
                                MetricNewBusinessDirector,
                                MetricHighDividendReleaseRatio,
                                MetricSupplierConcentrationRatios,
                                MetricCustomerConcentrationRatios,
                                MetricRegionalEconomyIndex,
                                DebtorDaysChangeValue_array,
                                MetricLargeVATBillToCapitalRatio
                                ), axis = 0)





signals_reshape_array = np.reshape(signals_array, (np.shape(signals_array)[0]// 2, 2))
print(signals_reshape_array)
    

[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0.8117120950423786 0.8117120950423786]
 [-4623.885446 -4623.885446]
 [0 0]
 [0 0]
 [0.17282565358114474 0.17282565358114474]
 [147.43649272436036 147.43649272436036]
 [False False]
 [5937.381530999999 5937.381530999999]
 [-0.700387599843812 -0.700387599843812]
 [-35.30298792998281 -35.30298792998281]
 [1.181309163942098 1.181309163942098]
 [0 0]
 [0 0]
 [0 0]
 [0.5100824831188121 0.5100824831188121]
 [0.0 0.0]
 [19.834706874339687 19.834706874339687]
 [0.06826802882319698 0.06826802882319698]
 [0.09244628903141258 0.09244628903141258]
 [0 0]
 [0 0]
 [1 0]
 [-0.42352974470891225 -0.42352974470891225]
 [1.0408319148007508 1.0408319148007508]
 [1.0408319148007508 1.0408319148007508]
 [8 6]
 [0 0]
 [-0.0006212975883659394 -0.0006212975883659394]]


In [89]:
thresholds_limits = np.concatenate((thresholdsll_df.iloc[1:,1:], thresholdsul_df.iloc[1:,1:]), axis=0)
rows, columns = np.shape(thresholds_limits)

threshold_limits_reshaped = np.reshape(thresholds_limits, (2, int(rows / 2), columns))

np.shape(threshold_limits_reshaped)
print(threshold_limits_reshaped)

[[[  nan   nan  0.     nan   nan   nan   nan   nan]
  [  nan   nan  0.     nan   nan   nan   nan   nan]
  [  nan   nan  0.     nan   nan   nan   nan   nan]
  [  nan   nan  0.3    nan   nan   nan   nan   nan]
  [  nan   nan  0.     nan   nan   nan   nan   nan]
  [ 2.     nan   nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan -0.33   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan -0.2    nan   nan]
  [  nan -0.2    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan   nan  1.     nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan  1.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan   nan   nan  0.5    nan   nan]
  [  nan  0.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan  0.5    nan   nan   nan   nan]
  [  nan  0.5    nan   nan   nan   nan   nan   nan]
  [  nan   nan   nan  0.5    nan   nan   nan   nan]
  [  nan  0.

In [92]:
thresholds_pts = np.concatenate((thresholdslpts_df.iloc[1:,1:], thresholdsupts_df.iloc[1:,1:]), axis=0)
rows, columns = np.shape(thresholds_pts)

threshold_pts_reshaped = np.reshape(thresholds_pts, (2, int(rows / 2), columns))

np.shape(threshold_pts_reshaped)

print(threshold_pts_reshaped)

[[[nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [nan nan  3. nan nan nan nan nan]
  [ 3. nan nan nan nan nan nan nan]
  [nan nan nan  3. nan nan nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan 10. nan nan nan nan nan nan]
  [nan nan nan nan nan  0.  3. nan]
  [nan nan nan nan nan  3. nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan nan nan  3. nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan  3. nan nan nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan  3. nan nan nan nan]
  [nan  3. nan nan nan nan nan nan]
  [nan nan nan nan nan nan nan  3.]
  [ 3. nan nan nan nan nan nan nan]
  [nan nan nan nan nan nan  3. nan]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan nan  3.]
  [nan nan nan nan nan nan  3. nan]
  [nan nan nan nan nan nan  

In [90]:
review_trigger_levels = np.transpose(np.array(review_trigger_levels_df.iloc[:,1:]))
print(review_trigger_levels)

[[4.  4.  0.5 3.  4.  4.  3.  4. ]]


In [93]:
metrics = signals_reshape_array
number_limits, number_metrics, number_risks = np.shape(threshold_limits_reshaped)

number_companies = 2
company = 0
lower_limit = 0
upper_limit = 1
lower_breach = np.zeros((number_metrics, number_risks, number_companies))
lower_score = np.zeros((number_metrics, number_risks, number_companies))
upper_breach = np.zeros((number_metrics, number_risks, number_companies))
upper_score = np.zeros((number_metrics, number_risks, number_companies))
company_lower_risk_score = np.zeros((number_risks, number_companies))
for company in range(number_companies) :
   for risk in range(number_risks) :
      lower_breach[:, risk, company] = metrics[:, company] > threshold_limits_reshaped[lower_limit, :, risk]
      lower_score[:, risk, company] =  lower_breach[:, risk, company] * threshold_pts_reshaped[lower_limit, :, risk]  
      upper_breach[:, risk, company] = metrics[:, company] > threshold_limits_reshaped[upper_limit, :, risk]
      upper_score[:, risk, company] =  upper_breach[:, risk, company] * threshold_pts_reshaped[upper_limit, :, risk]  
      final_score = np.maximum(lower_score, upper_score)   
company_final_risk_score = np.nanmean(final_score, axis=0) 
print(company_final_risk_score)

[[0.         0.        ]
 [0.83333333 0.83333333]
 [3.         0.        ]
 [1.66666667 1.66666667]
 [1.66666667 1.66666667]
 [3.         3.        ]
 [0.         0.        ]
 [2.         1.        ]]


<ipython-input-93-dd77b566150d>:15: RuntimeWarning: invalid value encountered in greater
  lower_breach[:, risk, company] = metrics[:, company] > threshold_limits_reshaped[lower_limit, :, risk]


In [94]:
risk_profile = np.zeros((number_risks, number_companies))
for company in range(number_companies) :
   risk_profile[:, company] = company_final_risk_score[:, company] > review_trigger_levels
print(risk_profile)    

[[0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [95]:
risk_signals = np.zeros((number_metrics, number_companies))
for company in range(number_companies) :
   risk_signals[:, company] = np.matmul(np.nan_to_num(final_score[:,:,company]), np.nan_to_num(np.transpose(company_final_risk_score[:, company]))) > 0
print(risk_signals)


header =  ["Party_id", "ValiDate", "DateCreated", "Description", "DescriptionDetail", "Action", "ActionData", "Weigthing", "Status", "Narrative", "QueueType"]
block = np.reshape(header, (1, 11))
for company in range(number_companies) :
    party_id = []
    ValidDate=[]
    DateCreated =[]
    Description = []
    DescriptionDetail = []
    Action = []
    ActionData = []
    Weighting = []
    Status = []
    Narrative = []
    QueueType = []
    count_signals = 0
    for metric in range(number_metrics) :
       if risk_signals[metric, company] > 0 :
          party_id = np.append(party_id, str(company))
          ValidDate= np.append(ValidDate, ["8/31/2020  12:00:00 AM"])
          DateCreated = np.append(DateCreated,["8/31/2020  12:00:00 AM"]) 
          Description = np.append(Description, signal_narrative_df['description detail'][metric])
          DescriptionDetail = np.append(DescriptionDetail, signal_narrative_df['description'][metric])
          Action =  np.append(Action, signal_narrative_df['action'][metric]) 
          ActionData = np.append(ActionData, [" "])
          Weighting = np.append(Weighting, [" "])
          Status = np.append(Status, ["Open"])
          if signal_narrative_df['insert'][metric] == 0 :
            Narrative = np.append(Narrative, signal_narrative_df['narrative'][metric])
          else :
            Narrative = np.append(Narrative, signal_narrative_df['narrative'][metric] + " {} ".format(metrics[metric, company]) +  signal_narrative_df['narrative2'][metric])
          QueueType = np.append(QueueType, signal_narrative_df['risk'][metric])
          count_signals += 1  
       next_block = np.concatenate((party_id, ValidDate, DateCreated, Description, DescriptionDetail, Action, ActionData, Weighting, Status, Narrative, QueueType), axis = 0)  
       cols = count_signals
       rows = 11
       next_block_reshape = np.reshape(next_block, (rows, cols))    
       next_block_reshape_transpose = next_block_reshape.T
    block = np.concatenate((block, next_block_reshape_transpose), axis=0)

print(block)                        
    
                        

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[['Party_id' 'ValiDate' 'DateCreated' 'Description' 'DescriptionDetail'
  'Action' 'ActionData' 'Weigthing' 'Status' 'Narrative' 'QueueType']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'A director has been disquaified.  ' 'Credit Risk' 'ViewDirectors' ' '
  ' ' 'Open'
  'A named director of the business has been registered as disqualified within the last 30 days.  This is in breach of credit policy and immediate intervention is required.'
  'Credit']
 ['0' '8/31/2020  12:00:00 AM' '8/31/2020  12:00:00 AM'
  'A director has sanctioned with a CCJ. ' 'Credit Risk'
  'ViewPublicRecords' ' ' ' ' 'Open'
  'A named director has registered as santioned with a CCJ withi

In [96]:

pd.DataFrame(block).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\signals.csv", header=None, index=None)


In [501]:
pd.DataFrame(block).to_sql('signals', conn, if_exists='replace', index = False)

In [97]:
header = [ 
"Id",
"PartyId",
"QueueType",
"DateCreated",
"Status",
"DateClosed"
]

header_queue = np.reshape(header, (1, len(header)))


In [98]:
block_queue = block[1:,[0, 10, 2]]
unique_block_queue = np.unique(block_queue, axis=0)
print(unique_block_queue)

[['0' 'AML' '8/31/2020  12:00:00 AM']
 ['0' 'Capital' '8/31/2020  12:00:00 AM']
 ['0' 'Conduct' '8/31/2020  12:00:00 AM']
 ['0' 'Contagion' '8/31/2020  12:00:00 AM']
 ['0' 'Credit' '8/31/2020  12:00:00 AM']
 ['0' 'Liquidity' '8/31/2020  12:00:00 AM']
 ['0' 'Trade' '8/31/2020  12:00:00 AM']
 ['1' 'AML' '8/31/2020  12:00:00 AM']
 ['1' 'Capital' '8/31/2020  12:00:00 AM']
 ['1' 'Conduct' '8/31/2020  12:00:00 AM']
 ['1' 'Contagion' '8/31/2020  12:00:00 AM']
 ['1' 'Liquidity' '8/31/2020  12:00:00 AM']
 ['1' 'Trade' '8/31/2020  12:00:00 AM']]


In [99]:
rows, cols = np.shape(unique_block_queue)
id = np.reshape([i for i in range(rows)], (rows,1)) 
#print(id)
status = np.reshape(["New"] * rows, (rows,1)) 
#print(status)
dateclosed = np.reshape([""] * rows, (rows,1)) 
np.shape(id)

(13, 1)

In [100]:
block_queue_out = np.concatenate ((header_queue, np.concatenate ((id, unique_block_queue, status, dateclosed), axis= 1)), axis=0)
print(block_queue_out)

[['Id' 'PartyId' 'QueueType' 'DateCreated' 'Status' 'DateClosed']
 ['0' '0' 'AML' '8/31/2020  12:00:00 AM' 'New' '']
 ['1' '0' 'Capital' '8/31/2020  12:00:00 AM' 'New' '']
 ['2' '0' 'Conduct' '8/31/2020  12:00:00 AM' 'New' '']
 ['3' '0' 'Contagion' '8/31/2020  12:00:00 AM' 'New' '']
 ['4' '0' 'Credit' '8/31/2020  12:00:00 AM' 'New' '']
 ['5' '0' 'Liquidity' '8/31/2020  12:00:00 AM' 'New' '']
 ['6' '0' 'Trade' '8/31/2020  12:00:00 AM' 'New' '']
 ['7' '1' 'AML' '8/31/2020  12:00:00 AM' 'New' '']
 ['8' '1' 'Capital' '8/31/2020  12:00:00 AM' 'New' '']
 ['9' '1' 'Conduct' '8/31/2020  12:00:00 AM' 'New' '']
 ['10' '1' 'Contagion' '8/31/2020  12:00:00 AM' 'New' '']
 ['11' '1' 'Liquidity' '8/31/2020  12:00:00 AM' 'New' '']
 ['12' '1' 'Trade' '8/31/2020  12:00:00 AM' 'New' '']]


In [101]:
pd.DataFrame(block_queue_out).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\queuev2.csv", header=None, index=None)

In [500]:
pd.DataFrame(block_queue_out).to_sql('queuev2', conn, if_exists='replace', index = False)

In [102]:
#cashflow
print(BS_df)

                          Line item        17-Dec       18-Jan        18-Feb  \
0                            Assets           NaN          NaN           NaN   
1                 Short-term Assets           NaN          NaN           NaN   
2                              Cash   34272.46377   26611.1117   25722.71960   
3               Accounts Receivable           NaN          NaN           NaN   
4                         Inventory   19000.00000   14250.0000   14250.00000   
5           Other Short-term Assets           NaN          NaN           NaN   
6           Total Short-term Assets   53272.46377   40861.1117   39972.71960   
7                  Long-term Assets       0.00000       0.0000       0.00000   
8                    Capital Assets       0.00000       0.0000       0.00000   
9          Accumulated Depreciation       0.00000       0.0000       0.00000   
10           Total Long-term Assets       0.00000       0.0000       0.00000   
11                     Total Assets   53

In [103]:
#np.shape(BS_df)
#type(BS_df)
BS_array = np.array(BS_df)[:, 1:]
#BS_assets_key_lines = BS_array[asset_key_lines]
rows, cols = np.shape(BS_array)
BS_array_prev = np.c_[np.zeros((rows, 1)), BS_array[:, 0:cols-1]]

#np.shape(BS_array[:, 0:cols-1])
#np.shape(np.zeros((rows, 1)))
#np.shape(BS_array[0: cols-1])

BS_movement = (BS_array - BS_array_prev)[:,1:]
#print(BS_movement)

BS_reshape_movement = np.reshape(BS_movement, (rows// number_companies, number_months-1, number_companies))
print(BS_reshape_movement)

[[[nan nan]
  [nan nan]
  [nan nan]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 [[-7661.352070000001 -888.3921000000009]
  [-894.4091499999995 -3582.8152900000023]
  [-1728.950929999999 -9036.03935]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 [[-4750.0 0.0]
  [-4750.0 0.0]
  [-2375.0 0.0]
  ...
  [nan nan]
  [nan nan]
  [nan nan]]

 ...

 [[0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  ...
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[-5641.178250000001 5399.483250000001]
  [-1646.1052500000005 4780.5562500000015]
  [-2034.7822500000002 803.1292499999981]
  ...
  [7755.265299999999 2135.426700000011]
  [20916.56880000001 11042.38499999998]
  [19649.151300000027 31808.862699999998]]

 [[-8122.952099999995 4037.257100000046]
  [-369.10530000005383 1890.5563000000548]
  [1756.2176999999792 -3643.8707000000286]
  ...
  [-5435.737399999984 -11204.978200000012]
  [-1294.3402999999817 -9131.244000000006]
  [-2003.9715999999898 -4623.885400000028]]]


In [104]:
BS_assets = ["Assets",
"Short-term Assets",
"Cash",
"Accounts Receivable",
"Inventory",
"Other Short-term Assets",
"Total Short-term Assets",
"Long-term Assets",
"Capital Assets",
"Accumulated Depreciation",
"Total Long-term Assets",
"Total Assets"
]


Assets_key_lines = [
"Accounts Receivable",
"Inventory",
"Other Short-term Assets",
"Long-term Assets",
]




type(BS_assets)

list

In [105]:
BS_liabilities = [
"Liabilities and Capital",
"Accounts Payable",
"Short-term Notes",
"Other Short-term Liabilities",
"Subtotal Short-term Liabilities",
"Long-term Liabilities",
"Total Liabilities",
"Paid in Capital",
"Dividends paid",
"Retained Earnings",
"Earnings",
"Total Capital",
"Total Liabilities and Capital",
"Net Worth"
]

Liabilities_key_lines = [
"Accounts Payable",
"Short-term Notes",
"Other Short-term Liabilities",
"Long-term Liabilities",
]



print(BS_liabilities)

['Liabilities and Capital', 'Accounts Payable', 'Short-term Notes', 'Other Short-term Liabilities', 'Subtotal Short-term Liabilities', 'Long-term Liabilities', 'Total Liabilities', 'Paid in Capital', 'Dividends paid', 'Retained Earnings', 'Earnings', 'Total Capital', 'Total Liabilities and Capital', 'Net Worth']


In [107]:
BS_array = np.array(BS_df)
BS_assets_key_lines = BS_array[np.isin(BS_array[:,0], Assets_key_lines)][:, 1:]

rows, cols = np.shape(BS_assets_key_lines)
BS_assets_key_lines_prev = np.c_[np.zeros((rows, 1)), BS_assets_key_lines[:, 0:cols-1]]

#np.shape(BS_array[:, 0:cols-1])
#np.shape(np.zeros((rows, 1)))
#np.shape(BS_array[0: cols-1])

BS_assets_movement = (BS_assets_key_lines - BS_assets_key_lines_prev)[:,1:]
#print(BS_assets_movement)


BS_reshape_assets_movement = np.moveaxis(np.reshape(BS_assets_movement, (  number_companies, number_months-1, rows//number_companies)), [0, 2], [2, 0])

#print(BS_assets_key_lines)

BS_positive_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement >= 0]
BS_negative_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement < 0]
#print(BS_positive_assets_movement)
#print(BS_negative_assets_movement)

#np.moveaxis(BS_reshape_assets_movement, [0, 1, 2], [2, 0, 1]).shape
#np.shape(BS_reshape_assets_movement)
print(BS_reshape_assets_movement)

[[[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [-4750.0 -4750.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]]

 [[nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [nan nan]
  [0.0 0.0]
  [0.0 0.0]
  [0.0 0.0]
  [0

<ipython-input-107-985e3cf2154d>:19: RuntimeWarning: invalid value encountered in greater_equal
  BS_positive_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement >= 0]
<ipython-input-107-985e3cf2154d>:20: RuntimeWarning: invalid value encountered in less
  BS_negative_assets_movement = abs(BS_reshape_assets_movement) * [BS_reshape_assets_movement < 0]


In [112]:
BS_array = np.array(BS_df)
BS_liabilities_key_lines = BS_array[np.isin(BS_array[:,0], Liabilities_key_lines)][:, 1:]

rows, cols = np.shape(BS_liabilities_key_lines)
BS_liabilities_key_lines_prev = np.c_[np.zeros((rows, 1)), BS_liabilities_key_lines[:, 0:cols-1]]

#np.shape(BS_array[:, 0:cols-1])
#np.shape(np.zeros((rows, 1)))
#np.shape(BS_array[0: cols-1])

BS_liabilities_movement = (BS_liabilities_key_lines - BS_liabilities_key_lines_prev)[:,1:]
#print(BS_assets_movement)


BS_reshape_liabilities_movement = np.moveaxis(np.reshape(BS_liabilities_movement, (  number_companies, number_months-1, rows//number_companies)), [0, 2], [2, 0])
print(BS_reshape_liabilities_movement[:,0,0])
#print(BS_assets_key_lines)

BS_positive_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement >= 0]
BS_negative_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement < 0]
print(BS_positive_liabilities_movement)
print(BS_negative_liabilities_movement)

[-2482.0 -742.0 1897.0 -2270.0]
[[[[0.0 0.0]
   [4411.0 4411.0]
   [5674.0 5674.0]
   [0.0 0.0]
   [3179.6692160000007 3179.6692160000007]
   [4090.1027270000004 4090.1027270000004]
   [0.0 0.0]
   [3891.3037829999994 3891.3037829999994]
   [5005.499359000001 5005.499359000001]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]]

  [[0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [0.0 0.0]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [nan nan]
   [

<ipython-input-112-a2fe70d709a4>:19: RuntimeWarning: invalid value encountered in greater_equal
  BS_positive_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement >= 0]
<ipython-input-112-a2fe70d709a4>:20: RuntimeWarning: invalid value encountered in less
  BS_negative_liabilities_movement = abs(BS_reshape_liabilities_movement) * [BS_reshape_liabilities_movement < 0]


In [108]:
Cashflow_lines = [
"Net Profit",
"Plus:",
"Depreciation",
"Change in Accounts Payable",
"Current Borrowing (repayment)",
"Increase (decrease) Other Liabilities",
"Long-term Borrowing (repayment)",
"Capital Input",
"Subtotal",
"Less:",
"Change in Accounts Receivable",
"Change in Inventory",
"Change in Other Short-term Assets",
"Capital Expenditure",
"Dividends",
"Subtotal",
"Net Cash Flow",
"Cash Balance",
]

type(Cashflow_lines)

list

In [109]:
Cashflow_lines = [
"Net Profit",
"Plus:",
"Depreciation",
"Change in Accounts Payable",
"Current Borrowing (repayment)",
"Increase (decrease) Other Liabilities",
"Long-term Borrowing (repayment)",
"Capital Input",
"Subtotal",
"Less:",
"Change in Accounts Receivable",
"Change in Inventory",
"Change in Other Short-term Assets",
"Capital Expenditure",
"Dividends",
"Subtotal",
"Net Cash Flow",
"Cash Balance",
]

standard_cashflow_lines =[
"Operating cash flow",
"Net earnings",
"Plus: depreciation and amortisation",
"Less:  changes in Working capital",
"Cash from operations",
"Investing cashflow",
"Investments in property & equipment",
"Cash from investing",
"Financing cashflow",
"Issuance (repayment) of debt",
"Issuance (repayment) of equity",
"Cash from Financing",
"Net increase (decrease) in cash",
"Opening cash",
"Closing cash"
]

standard_cashflow_lines_mapping ={
"Net Profit" : ["Net earnings", "plus"],
"Plus:" : ["text", "text"],
"Depreciation" : ["plus: depreciation and amortisation", "plus"],
"Change in Accounts Payable" : ["Less: changes in Working capital", "less"],
"Current Borrowing (repayment)" : ["Issuance (repayment) of debt", "plus"],
"Increase (decrease) Other Liabilities" : ["Less: changes in Working capital", "less"],
"Long-term Borrowing (repayment)" : ["Issuance (repayment) of debt", "plus"],
"Capital Input" : ["Issuance (repayment) of equity", "plus"],
"Subtotal" : ["text", "text"],
"Less:" : ["text", "text"],
"Change in Accounts Receivable" : ["Less:  changes in Working capital", "less"],
"Change in Inventory" : ["Less:  changes in Working capital", "less"],    
"Change in Other Short-term Assets" : ["Less:  changes in Working capital", "less"],
"Capital Expenditure" : ["Investments in property & equipment", "less"],
"Dividends" : ["Issuance (repayment) of equity", "plus"],
"Net Cash Flow" : ["rec", "sum"],
"Cash Balance" : ["Closing cash", "rec"]
}



In [110]:
to = 0
sign = 1

print(standard_cashflow_lines_mapping["Net Profit"][to])
print(standard_cashflow_lines_mapping["Net Profit"][sign])
#print(Cashflow_lines)

Net earnings
plus


In [121]:
#print(BS_array)

BS_assets_standard_lines = BS_array[np.isin(BS_array[:,0], standard_cashflow_lines_mapping.keys)][:, 1:]

print(BS_assets_standard_lines)



[]


In [430]:
Pnl_and_BS_adj_array = np.concatenate((PATValue[1:,:], DepreciationValue[1:,:]), axis= 0)
nrows, ncols = np.shape(Pnl_and_BS_adj_array)
Pnl_and_BS_adj_reshape_array = np.reshape(Pnl_and_BS_adj_array, (nrows// (number_months-1) , number_months-1, number_companies))

Paidin_cap_reshape_array = np.reshape(PaidInCapitalValue[1:,:], (1 , number_months-1, number_companies))

Div_and_Cash_array = np.concatenate((PaidInCapitalValue[1:,:], DepreciationValue[1:,:]), axis= 0)
nrows, ncols = np.shape(Div_and_Cash_array)
Div_and_Cash_reshape_array = np.reshape(Div_and_Cash_array, (nrows// (number_months-1) , number_months-1, number_companies))

#print (Div_and_Cash_reshape_array)
#np.shape(Div_and_Cash_reshape_array)
#np.shape(BS_reshape_assets_movement)

In [432]:
#np.shape(Pnl_and_BS_adj_array)
np.shape(BS_reshape_assets_movement)

(4, 35, 2)

In [433]:
cashflow_array = np.concatenate((Pnl_and_BS_adj_reshape_array,
                                -1 * (BS_reshape_assets_movement),
                                Paidin_cap_reshape_array,
                                BS_reshape_liabilities_movement,
                                Div_and_Cash_reshape_array                                 
                                ), axis = 0)


np.shape(cashflow_array)
print(cashflow_array)

[[[-9929.352071 -9929.352071]
  [473.6079057 473.6079057]
  [-6921.409154000001 -6921.409154000001]
  [-692.815291 -692.815291]
  [-7894.950923 -7894.950923]
  [-4589.039350999999 -4589.039350999999]
  [-10396.54553 -10396.54553]
  [298.531136 298.531136]
  [-7810.632797 -7810.632797]
  [-633.5234582 -633.5234582]
  [-2143.6559850000003 -2143.6559850000003]
  [16094.132480000002 16094.132480000002]
  [-10124.816429999999 -10124.816429999999]
  [72.88637183 72.88637183]
  [-7284.038479999999 -7284.038479999999]
  [-1012.977667 -1012.977667]
  [-8191.7618760000005 -8191.7618760000005]
  [-4786.269061999999 -4786.269061999999]
  [-10611.781790000001 -10611.781790000001]
  [-47.0708586 -47.0708586]
  [-8146.245784000001 -8146.245784000001]
  [-926.8495602 -926.8495602]
  [-2751.8127 -2751.8127]
  [12301.80926 12301.80926]
  [-10883.41833 -10883.41833]
  [-1124.026954 -1124.026954]
  [-8471.848918000002 -8471.848918000002]
  [-2062.566803 -2062.566803]
  [-9280.226391 -9280.226391]
  [-5435

In [434]:
np.shape(BS_reshape_assets_movement)

(4, 35, 2)

In [438]:
header = [ 
"party_id",
"month",
"Net Profit",
"Depreciation",
"Change in Accounts Payable",
"Decrease in Current Borrowing (repayment)",
"Increase (decrease) Other Liabilities",
"Decrease in Long-term Borrowing (repayment)",
"Capital Input",
"Change in Accounts Receivable",
"Change in Inventory",
"Change in Other Short-term Assets",
"Change in LT/ Capital Assets",
"Dividends",
"Cash Balance"
]

header_cashflow = np.reshape(header, (1, len(header)))


In [440]:
cashflow_months = months[1:]
cashflow_out = np.reshape(cashflow_array, (len(cashflow_months) * number_companies, len(header)-2))
np.shape(cashflow_out)

(70, 13)

In [441]:


number_cashflow_months = len(cashflow_months)
party_id =  np.reshape(([np.ones(number_cashflow_months) * company for company in range(number_companies)]),  (number_companies * number_cashflow_months, 1) )
#np.shape(party_id)
cashflow_months_out = np.reshape(cashflow_months*number_companies, (len(cashflow_months*number_companies), 1))
np.shape(cashflow_months_out)
#np.shape(cashflow_out)

(70, 1)

In [442]:
block_cashflow = np.concatenate((party_id, cashflow_months_out, cashflow_out), axis = 1)
#block_cashflow_out = np.concatenate((header, block_cashflow), axis = 1)

In [443]:
#np.shape(block_cashflow)
block_cashflow_out = np.concatenate((header_cashflow, block_cashflow), axis = 0)

In [444]:
pd.DataFrame(block_cashflow_out).to_csv("\\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\cashflowv2.csv", header=None, index=None)

In [499]:
pd.DataFrame(block_cashflow_out).to_sql('cashflowv2', conn, if_exists='replace', index = False)

In [445]:
# nba customer embedding

ESG_risk = np.reshape([0] * number_companies, (1, number_companies))
#past_repayment_history = np.reshape([0] * number_companies, (1, number_companies))
#lodgements_in_bank_account_in_last_3months = np.reshape([0] * number_companies, (1, number_companies))
EBITDA = np.reshape([0] * number_companies, (1, number_companies))
adjusted_EBITDA = np.reshape([0] * number_companies, (1, number_companies)) #(captial withdrawals added back in) 
funding_gap = np.reshape([0] * number_companies, (1, number_companies)) # of business 
#IsUsing_all_facilities_already_paid_for = np.reshape([0] * number_companies, (1, number_companies)) #e.g. overdraft (intra day)
#age_of_account = np.reshape([0] * number_companies, (1, number_companies))
overseas_invoices_ge_50k = np.reshape([0] * number_companies, (1, number_companies))
DigitalRetailerNegCCC = np.reshape([0] * number_companies, (1, number_companies))
UnencumberedAsset = np.reshape([0] * number_companies, (1, number_companies))
InvoiceOpportunity = np.reshape([0] * number_companies, (1, number_companies))
AssetNearEndOfLife = np.reshape([0] * number_companies, (1, number_companies))



In [487]:
#type(datetime.datetime.now())
#type(commercial_df['date of incorporation'])
#type(commercial_df['date of incorporation'].dt)
#type(pd.to_datetime(commercial_df['date of incorporation']).dt)
#print(pd.to_datetime(commercial_df['date of incorporation']))

#t = ((datetime.datetime.now() - pd.to_datetime(commercial_df['date of incorporation']))/ np.timedelta64(1, 'D')).astype(int)
#print(t/30)

In [488]:
import datetime

age_of_account = np.array(((datetime.datetime.now() - pd.to_datetime(commercial_df['date of incorporation']))/ np.timedelta64(1, 'D')).astype(int)) /30
#print(age_of_account)
age_of_account_reshape = np.reshape(age_of_account, (1, number_companies))
#age_of_account_reshape.shape


In [489]:
past_repayment_history = np.array(OpenBanking_df['lending in arrears'])
past_repayment_history_reshape = np.reshape(past_repayment_history, (1, number_companies))
lodgements_in_bank_account_in_last_3months = np.array(OpenBanking_df['lodgement in last 3 months'])
lodgements_in_bank_account_in_last_3months_reshape = np.reshape(lodgements_in_bank_account_in_last_3months, (1, number_companies))
#past_repayment_history.shape
#print(past_repayment_history)

In [490]:
IsUsing_all_facilities_already_paid_for = (np.array(OpenBanking_df['overdraft limit']) + np.array(OpenBanking_df['current account balance'])) >0
IsUsing_all_facilities_already_paid_for_reshape = np.reshape(IsUsing_all_facilities_already_paid_for, (1, number_companies))


In [491]:
customer_embedding_array = np.concatenate((risk_profile,
                                           ESG_risk,
                                           past_repayment_history_reshape,
                                           lodgements_in_bank_account_in_last_3months_reshape,
                                           EBITDA,
                                           adjusted_EBITDA,
                                           funding_gap,
                                           IsUsing_all_facilities_already_paid_for_reshape,
                                           age_of_account_reshape,
                                           overseas_invoices_ge_50k,
                                           DigitalRetailerNegCCC,
                                           UnencumberedAsset,
                                           InvoiceOpportunity,
                                           AssetNearEndOfLife                              
                                          ), axis = 0)


In [492]:
#score = np.matmul(NBA_scorecard_array, customer_embedding_array )
#np.shape(score)
NBA_scorecard_array=np.array(NBA_scorecard_df)[2:,2:]

#type(customer_embedding_array)
score = np.matmul(NBA_scorecard_array.astype(float), customer_embedding_array.astype(float) )
np.shape(score)
print(score)

number_actions = np.shape(score)[0]
order = np.argsort(-score, axis=0)
print(number_actions)


[[ 0.00000000e+00  0.00000000e+00]
 [-9.99000000e+02 -9.99000000e+02]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.00000000e+00  5.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.00000000e+01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.20000000e+01  1.00000000e+00]
 [ 1.38133333e+03  2.64666667e+02]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00]]
18


In [493]:
header = [ 
"Id",
"PartyId",
"QueueType",
"Fit Score",
"DateCreated",
"Status",
"DateClosed"
]

header_nba = np.reshape(header, (1, len(header)))

print(header_nba)

[['Id' 'PartyId' 'QueueType' 'Fit Score' 'DateCreated' 'Status'
  'DateClosed']]


In [494]:
block = np.reshape(header, (1, len(header)))
count_all_nba = 0
for company in range(number_companies) :
    id = []
    party_id = []
    QueueType=[]
    Fit_score =[]
    DateCreated = []
    Status = []
    DateClosed = []
    count_nba = 0
    for action in range(number_actions) :
       if score[action, company] > 0 :
          id = np.append(id, count_all_nba)
          party_id = np.append(party_id, str(company))
          QueueType = np.append(QueueType, actions_df.loc[action][1])  
          Fit_score= np.append(Fit_score, score[action, company])
          DateCreated = np.append(DateCreated,["8/31/2020  12:00:00 AM"]) 
          Status = np.append(Status, ["Open"])
          DateClosed = np.append(DateClosed,[""])   
          count_nba += 1  
          count_all_nba += 1
       next_block = np.concatenate((id, party_id, QueueType, Fit_score, DateCreated, Status, DateClosed), axis = 0)  
       cols = count_nba
       rows = len(header)
       next_block_reshape = np.reshape(next_block, (rows, cols))    
       next_block_reshape_transpose = next_block_reshape.T
    block = np.concatenate((block, next_block_reshape_transpose), axis=0)

print(block)                        

[['Id' 'PartyId' 'QueueType' 'Fit Score' 'DateCreated' 'Status'
  'DateClosed']
 ['0.0' '0'
  'Conduct - improve efficiency of current finance facilities - use of fx facility (rates) - criteria check : fx margin observed vs offered rate'
  '5.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['1.0' '0'
  'Liquidity - support business owners growth objectives - support expanded sales growth through cashflow support e.g export credit lines, invoice finance - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and overseas invoices'
  '50.0' '8/31/2020  12:00:00 AM' 'Open' '']
 ['2.0' '0'
  'Contagion - sustain and protect business - interest rate and fx hedge products - criteria check : mature (> 5+ years) and stable (4 of 5 YOY growth) business and  interest rate volitility / earnings or fx volitility / earnings> threshold.  Large earnings residual risk due to rigid mis alignment of contract terms between supply vs demand markets'
  '12.0' '8/31/2020  12:00:00 AM' 'Open' 

In [495]:
print(actions_df.loc[1][1])

Fraud - Investigate - due diligence to establish legitimacy and authenticity of business


In [496]:
pd.DataFrame(block).to_csv(r"\Users\kenhr\OneDrive\Documents\Ken\OBR\Analytical kernel\NextBestActionv2.csv", header=None, index=None)

In [498]:
pd.DataFrame(block).to_sql('NextBestActionv2', conn, if_exists='replace', index = False)